param(
  [string]$OutFile = "src/data/releaseMediaManifest.ts"
)

$ErrorActionPreference = "Stop"

$projectRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
$outPath = Join-Path $projectRoot $OutFile
$versions = [ordered]@{}

function Add-MediaVersion {
  param(
    [string]$SourcePath,
    [string]$AssetName
  )

  if (-not (Test-Path -LiteralPath $SourcePath)) {
    return
  }

  $item = Get-Item -LiteralPath $SourcePath
  $stamp = $item.LastWriteTimeUtc.ToString("yyyyMMddHHmmss")
  $versions[$AssetName] = "$($item.Length)-$stamp"
}

$videoBay = Join-Path $projectRoot "public/videos/fpv-lab-background.mp4"
Add-MediaVersion -SourcePath $videoBay -AssetName "video-bay__fpv-lab-background.mp4"

$groups = @(
  @{ Group = "fpv-flight-video"; Path = "public/media/fpv-flight-video" },
  @{ Group = "deal-results-showcase"; Path = "public/media/deal-results-showcase" }
)

foreach ($group in $groups) {
  $dir = Join-Path $projectRoot $group.Path
  if (-not (Test-Path -LiteralPath $dir)) {
    continue
  }

  Get-ChildItem -LiteralPath $dir -File |
    Where-Object { $_.Extension -match '^\.(mp4|m4v|mov|webm)$' } |
    Sort-Object Name |
    ForEach-Object {
      $assetName = "$($group.Group)__$($_.BaseName)$($_.Extension.ToLowerInvariant())"
      Add-MediaVersion -SourcePath $_.FullName -AssetName $assetName
    }
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("// Generated by scripts/generate-release-media-manifest.ps1. Do not edit by hand.")
$lines.Add("export const releaseMediaVersionByAsset: Record<string, string> = {")

foreach ($key in ($versions.Keys | Sort-Object)) {
  $safeKey = $key.Replace("\", "\\").Replace("'", "\'")
  $safeValue = $versions[$key].Replace("\", "\\").Replace("'", "\'")
  $lines.Add("  '$safeKey': '$safeValue',")
}

$lines.Add("};")

$outDir = Split-Path -Parent $outPath
if (-not (Test-Path -LiteralPath $outDir)) {
  New-Item -ItemType Directory -Force -Path $outDir | Out-Null
}

Set-Content -LiteralPath $outPath -Value $lines -Encoding UTF8
Write-Host "Generated $OutFile with $($versions.Count) media entries."
