// Generated by scripts/prepare-media-variants.ps1 after FFmpeg creates poster/preview/full media.
// The checked-in empty map keeps the app safe before CDN variants are generated.
export const mediaVariantVersionByAsset: Record<string, string> = {};

export type MediaVariantManifestEntry = {
  key: string;
  group: string;
  id: string;
  posterAsset?: string;
  previewAsset?: string;
  fullAsset?: string;
  releasePosterAsset?: string;
  releasePreviewAsset?: string;
  releaseFullAsset?: string;
  width?: number;
  height?: number;
  duration?: number;
  variantHash?: string;
};

export const mediaVariantManifest: Record<string, MediaVariantManifestEntry> = {};
